### ISSUE TITLE
What is the icon theme?

### ISSUE THREAD

**Issue by asciidiego** [Alexdaz/Cosmic-Travel#1]
Maybe you should list it on the `README.md` file. :smile:

**Comment by Alexdaz** [comment]
¡Qué onda amigo!
Gracias por tu comentario, sip haré eso y de cualquier forma te paso el link y el nombre. 
[Plane icon theme for Mangenta](https://www.gnome-look.org/p/1183367/)

**Comment by asciidiego** [comment]
¡Gracias bro! :)
